### PR TITLE
Fix endless loop.

### PR DESCRIPTION
**Pull request by UniQP**
Seems that the code was never tested.

### CODE REVIEW

**Comment by oehhar** [comment]
Could you please check, if this is fixed in:

https://sourceforge.net/p/zint/code/ci/6158a95bd5969bf18f3d291a9cb04bd75bea41b8/tree/

Thank you,
Harald

**Comment by UniQP** [comment]
It is. So why is the github repository not up to date?

**Comment by oehhar** [comment]
;-)

**Comment by gitlost** [comment]
HI as an equivalent fix is already in the SourceForge repository am closing this. Please see https://sourceforge.net/p/zint/ if you've any further contributions, thanks.

**Pull request closed without merging**
